# Generated by Django 3.1.5 on 2021-03-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0010_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='mma_experience_level',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_units',
            field=models.CharField(default='pounds', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
