# Generated by Django 3.1.5 on 2021-05-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scout', '0011_auto_20210303_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='draws',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='losses',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='wins',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
